### ISSUE TITLE
Add parliament and ethnicity information to `dim_members`

### ISSUE THREAD

**Issue by jonfoong** [jeremychia/singapore-parliament-speeches-dbt#28]
`dim_members` currently shows one row per member. Instead we should have one row per member per parliament, with each row representing that member and the corresponding constituency, etc

I can add the ethnicity somewhere else manually and then maybe you can do the rest? @jeremychia

**Comment by jonfoong** [comment]
have created a dt with ethnicities under prod_dim.dim_members_ethnicity, though there are a couple I am unsure of (walter theseira, michael palmer, etc)

**Comment by jeremychia** [comment]
> dim_members currently shows one row per member. Instead we should have one row per member per parliament

i disagree. this contradicts the 3NF [modelling principle](https://en.wikipedia.org/wiki/Third_normal_form#:~:text=Third%20normal%20form%20(3NF)%20is,integrity%2C%20and%20simplify%20data%20management.). 

the purpose of a `dim_members` table is to answer information about each member. most of these attributes do not change with time. for example, the member's birth year, ethnicity, picture, do not change in relation to the parliaments their in.

it is also more memory-efficient to nest the changing attributes as an array (rather than to have multiple rows for each member). for example, this is how it is implemented:

![image](https://github.com/user-attachments/assets/fb2ed69f-60e6-4f0d-882e-7336f730df17)

for sun xueling, her entry is one row, but she has multiple appointments that are listed under `latest_member_appointments`.

i do agree with your point, however, that this information should be obvious on a member level. i will remodel the data to reflect this. thank you!

**Comment by jeremychia** [comment]
as for the ethnicity data, i prefer to model it slightly differently to keep it consistent with how other supplementary information is being done. i will share this with you when it's done:

for example:
` members_year_of_birth `

https://console.cloud.google.com/bigquery?ws=!1m5!1m4!4m3!1ssingapore-parliament-speeches!2sraw!3smembers_year_of_birth

**Comment by jonfoong** [comment]
Ok yes it seems inefficient to duplicate per row, what is simpler then is another column `parliament` with parliament numbers that the member was in
